#!/usr/bin/env python3
# Copyright (c) 2020 The Plankton Authors.
# All rights reserved.
#
# This source code is derived from UUV Simulator
# (https://github.com/uuvsimulator/uuv_simulator)
# Copyright (c) 2016-2019 The UUV Simulator Authors
# licensed under the Apache license, Version 2.0
# cf. 3rd-party-licenses.txt file in the root directory of this source tree.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import roslib
import os
import rclpy
import argparse
import sys
import shutil

from ament_index_python.packages import get_package_share_directory


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Create new colcon package for a UUV robot description")
    parser.add_argument('--robot_name', type=str)
    
    args = parser.parse_args(rclpy.utilities.remove_ros_args(sys.argv)[1:])
    #args = parser.parse_args(rospy.myargv()[1:])

    if args.robot_name is None:
        print('No robot name given!')
        sys.exit(-1)

    colcon_pkg = args.robot_name + '_description'

    print('Create new colcon package for a UUV robot description')
    print('\tRobot name = ' + args.robot_name)
    print('\tColcon package name = ' + colcon_pkg)

    if colcon_pkg is not None:
        if os.path.exists(colcon_pkg):
            print('Colcon package already exists!')
            sys.exit(1)
        print('Creating the colcon package...')
        os.system('ros2 pkg create --build-type ament_cmake ' + colcon_pkg)
        if not os.path.isdir(colcon_pkg):
            print('Colcon package could not be created')
            sys.exit(-1)
        print('Done!')

    template_path = os.path.join(get_package_share_directory('uuv_assistants'), 'templates', 'robot_model')

    for d in os.listdir(template_path):
        new_folder = os.path.join(colcon_pkg, d)
        os.makedirs(new_folder)
        print('Creating folder=' + new_folder)

        for f in os.listdir(os.path.join(template_path, d)):
            print('Creating file:')
            filename = os.path.join(colcon_pkg, d, f.replace('.template', ''))
            print('\t' + filename)

            output_file = open(filename, 'w')
            with open(os.path.join(os.path.join(template_path, d), f), 'r') as d_file:
                for line in d_file:
                    if '$ROBOT_NAME' in line:
                        line = line.replace('$ROBOT_NAME', args.robot_name)
                    if '$COLCON_PACKAGE' in line:
                        line = line.replace('$COLCON_PACKAGE', colcon_pkg)
                    output_file.write(line)

    print('Robot description package <%s> create successfully' % colcon_pkg)
